### PR TITLE
[ID-609] update workbench-libs to upgrade transitive dependency jose4j

### PR DESCRIPTION
**Pull request by Shakespeared**
Ticket: [Link to Jira ticket](https://broadworkbench.atlassian.net/browse/ID-609)

What:

Upgrading `jose4j` from 0.92 to 0.93 fixes a security vulnerability. It has recently been upgraded in workbench-libs (about 2 days ago), so just pulling the new version into Sam

### CODE REVIEW

**Review by tlangs — COMMENTED** [review]
Oh wow, did every library need an upgrade in minor version?

**Comment by Shakespeared** [comment]
> Oh wow, did every library need an upgrade in minor version?

They were all bumped in the same PR in workbench-libs, we don't really need to pull in all the new versions at once for this specific security issue (google2 is the one with the specific dep I wanted to upgrade) but it seemed like this block is written to be updated as a unit so I went ahead and bumped everything. If you think it's better to just do the single upgrade I can put the rest back

**Review by tlangs — APPROVED** [review]
Yeah, might as well stay up-to-date. Approvalled.

**Comment by Shakespeared** [comment]
jenkins retest

**Comment by Shakespeared** [comment]
jenkins retest

**Comment by Shakespeared** [comment]
jenkins retest

**Comment by Shakespeared** [comment]
jenkins retest

**Comment by Shakespeared** [comment]
jenkins retest

**Comment by Shakespeared** [comment]
jenkins retest

**Comment by Shakespeared** [comment]
jenkins retest

**Comment by Shakespeared** [comment]
jenkins retest c'mon

**Comment by Shakespeared** [comment]
jenkins retest

**Pull request merged**
