### PR TITLE
[DC-754] Add update_snapshot_builder_settings action

### PR DESCRIPTION
**Pull request by s-rubenstein**
Ticket: https://broadworkbench.atlassian.net/browse/DC-754

What:

Adds an action to update snapshot builder configuration.

Why:

  \<For your reviewers' sake, please describe in ~1 paragraph what the value of this PR is to our users or to ourselves.\>

How:

  \<For your reviewers' sake, please describe in ~1 paragraph how this PR accomplishes its goal.\>

  \<If the PR is big, please indicate where a reviewer should start reading it (i.e. which file or function).\>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

### CODE REVIEW

**Review by nmalfroy — APPROVED** [review]
lgtm!

**Review by pshapiro4broad — APPROVED** [review]
This seems OK. I was thinking an existing action might make sense like `edit_dataset` but I don't see that action used in TDR (not sure why) and it doesn't hurt to have a finer grained action right now. If we want to consolidate later on we can do it then.

**Comment by nmalfroy** [comment]
> This seems OK. I was thinking an existing action might make sense like `edit_dataset` but I don't see that action used in TDR (not sure why) and it doesn't hurt to have a finer grained action right now. If we want to consolidate later on we can do it then.

Actually, that's a good point, the `manage_schema` action had that in mind.  The problem is that it's not limited to admins.  Eventually, we may want to get rid of this action and just use `manage_schema` for updating the config (since it's really just dataset metadata)

**Comment by s-rubenstein** [comment]
Yeah, I think the other question for the Snapshot Builder is if we would want to open it to everyone - I think eventually yes, but probably not right now.

**Pull request merged**
