### PR TITLE
ID-607 Sam Local pulls server crt and key from k8s

### PR DESCRIPTION
**Pull request by tlangs**
Ticket: https://broadworkbench.atlassian.net/browse/ID-607

What:

DevOps removed the server crt and key from `firecloud-develop` and created a new local cert that is automatically renewed. Huzzah! Now, Sam local need to get those from k8s.

Why:

Down with `firecloud-develop`!

How:

Made `render_config.sh` pull the server crt and key from k8s instead of relying on them being rendered by `firecloud-develop`. Made the `run-proxy.sh` script point to the new secrets too.
---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

### CODE REVIEW

**Review by Shakespeared — APPROVED** [review]

**Comment by tlangs** [comment]
jenkins retest

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Comment by em-may** [comment]
@tlangs I updated the title and comment to reflect the current state of the diff since I pushed more commits. Sam local dev no longer relies on firecloud-develop config renders!

**Comment by tlangs** [comment]
@em-may I removed the `localhost` link, since it doesn't match the cert and gives a security warning.

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Pull request merged**
