### PR TITLE
[CA-1146] skip tests - readme - UML key

### PR DESCRIPTION
**Pull request by andy7i**
Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

### CODE REVIEW

**Review by gpolumbo-broad — APPROVED** [review]
I'm slightly worried that this is a 3rd party site that might change at any given time.  I might point at something like the wikipedia page https://en.wikipedia.org/wiki/Class_diagram which is less likely to go away or become unreachable.  That said, it's perhaps less digestible too.

**Comment by andy7i** [comment]
@gpolumbo-broad that's a very legit concern. I would propose that we cross that bridge once we get to it? Maybe the wikipedia page will have improved by then 🙃

**Review by dvoet — APPROVED** [review]
ok to use admin to merge

**Comment by andy7i** [comment]
using admin permissions to merge without tests (this is a doc change so tests aren't needed)

**Pull request merged**
