### PR TITLE
GAWB-3568 ActionPatterns defined as objects

### PR DESCRIPTION
**Pull request by gpolumbo-broad**
See old PR: https://github.com/broadinstitute/sam/pull/145

Created this branch to rebase the changes off of develop.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by gpolumbo-broad** [comment]
jenkins retest

**Comment by gpolumbo-broad** [comment]
Not sure why a test failed.  It's passing for me locally.  Try jenkins retest before spending too much more time on it

**Comment by gpolumbo-broad** [comment]
This time a Leo test failed...  moving targets, perhaps jenkins retest will fix it?

**Review by dvoet — APPROVED** [review]

**Comment by gpolumbo-broad** [comment]
jenkins retest - failed in Leo this time...

**Review by MatthewBemis — APPROVED** [review]

**Pull request merged**
