### PR TITLE
QA-2069: Identify bottleneck for slow contract tests. Optimize contract tests workflow.

### PR DESCRIPTION
**Pull request by ichengchang**
Ticket: [QA-2069](https://broadworkbench.atlassian.net/browse/QA-2069)

What:

We observed that tests can execute in far less time than the overall GHA workflow. This ticket explores strategies to improve the overall GHA workflow.

Why:

ID bottlenecks and present in the `dsp-contract-testing` channel or in the next early adopter’s meeting. 

Come up with a proposal to resolve bottlenecks.

How:

A combination of caching strategies help improve the overall workflow speed by reducing unnecessary compilation or dependency downloads.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

[QA-2069]: https://broadworkbench.atlassian.net/browse/QA-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ichengchang** [comment]
jenkins retest

**Review by gpolumbo-broad — APPROVED** [review]

**Comment by gpolumbo-broad** [comment]
Love the thorough commenting 👍

**Comment by ichengchang** [comment]
jenkins retest

**Comment by ichengchang** [comment]
jenkins retest

**Review by Shakespeared — APPROVED** [review]

**Pull request merged**
