### PR TITLE
Sam GroupApiSpec test

### PR DESCRIPTION
**Pull request by aweng98**
Jira [QA-493](https://broadworkbench.atlassian.net/browse/QA-493)
depend on [workbench-lib PR 221](https://github.com/broadinstitute/workbench-libs/pull/221)

### CODE REVIEW

**Comment by aweng98** [comment]
jenkins retest

**Review by dvoet — COMMENTED** [review]
why does this test do rawls stuff... sam tests should know nothing of rawls

**Comment by ansingh7115** [comment]
tbh I think these tests belong in rawls.

**Comment by aweng98** [comment]
@dvoet Because mimicking UI actions or/and performing verifications. For example, `Rawls.billing.removeUserFromBillingProject`, I don't know another way doing it without touching Rawls stuff.

**Comment by aweng98** [comment]
@ansingh7115 If it's a Rawls api tests, I would still need Sam stuff in tests. I thought about it before, either in Sam or Rawls, tests kind needs little of both.

**Comment by ansingh7115** [comment]
Sorry, accidentally deleted my comment. -_-
Original comment was these tests should be in rawls.
@aweng98  if it needs both, put it in rawls. Rawls has a dependency on sam, so it's appropriate to call sam from a rawls test. It's not appropriate to call rawls from a sam test because Sam does _not_ have a dependency on rawls.

**Comment by aweng98** [comment]
@asingh7115 ah, I'll redo it in Rawls. thank you.

**Pull request closed without merging**
