### PR TITLE
Policy is a subject

### PR DESCRIPTION
**Pull request by dvoet**
https://broadinstitute.atlassian.net/browse/GAWB-2785

The problem in the bug is that policies are groups but some of the code was not expecting that. But a policy was not a group in the code but contained a group. But that was also a little weird. So I restructured a bit.

review also https://github.com/broadinstitute/workbench-libs/pull/37

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by breilly2 — APPROVED** [review]
👍 Definitely some good improvements to the model. Just a couple of general thoughts that are probably larger in scope than this PR. I'd have to fiddle with the code to make concrete suggestions so I'm providing this mostly as food for thought.

`ValueObject` doesn't seem to me to be adding a lot of... well... value. It just wraps a `String` and provides a `value` property and some JSON handling. The name also conflicts with my prior notion of a "value object" that could encapsulate multiple properties. I wonder if there's a more specific notion than "value" that we're trying to express here. Maybe some renaming would help but I don't have specific suggestions.

Two things about the `WorkbenchGroup` hierarchy give me pause: the need for a concrete `BasicWorkbenchGroup` and the fact that you seem to cringe every time you have to describe an `AccessPolicy` as being a group. Smells like composition might be better but I don't know how much that would disrupt the model.

Lastly, I'll capture here that we talked a little bit as a group about whether or not the model should be merged into a single artifact (either sam itself of a separate model artifact from sam) instead of being split between sam and workbench-libs. Consolidating would allow us to seal the traits and avoid the catch-all case when matching.

**Comment by dvoet** [comment]
I cringe a little when I say a policy *is a* group instead of *contains a* group because this is a case where an implementation detail is driving our model. In order to implement list functionality efficiently and with minimum ick policies are groups in ldap. We tried modeling policies as if they contained a group but that wasn't working so well which is what this PR fixes.

**Comment by dvoet** [comment]
on the BasicWorkbenchGroup front, that is just scala being mean. We can't extend case classes so we need a trait and a concrete class.

**Comment by breilly2** [comment]
Thanks for the follow-up. You've probably said all of that before but the repetition is helpful. Could you add a code comment near `AccessPolicy` with that explanation of why a policy is a group?

**Pull request merged**
