### PR TITLE
WIP: Dockstore Resource Type

### PR DESCRIPTION
**Pull request by coverbeck**
Add a resource type for Dockstore resources.

I went with the name `tool`, because of Dockstore implements the Tool Registry Service (TRS).  Dockstore has the concept of both tools and workflows, but just like with TRS we can distinguish the two by path, prepending `#workflow/` to the path for workflows.

In other words, the resource id for the workflow `dockstore.org/myworkflow` would be, with the escaped characters,`%23workflow%2Fdockstore.org%2Fmyworkflow`, and the resource id for the tool `dockstore.org/mytool`would be `dockstore.org%2Fmytool`.

We currently only plan to support sharing for workflows in the first iteration, but we may support tools later.

I made this a WIP; looking for feedback, with these questions in particular:

1. Is the name `tool` too generic? Do we want to call it `dockstore-tool`, `dockstore-workflow` or something like that?
2. Should we have separate resource types for Dockstore tools and workflows, or put both Dockstore types under the single SAM resource type, like I currently have it?
3. How do the roles and actions I've defined seem? I've kept it fairly simple, but I don't know if I'm missing anything.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [  ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by dvoet — APPROVED** [review]

**Comment by dvoet** [comment]
ok to test

**Comment by geoffjentry** [comment]
I would suggest avoiding the word `tool`, it's too heavily overloaded ... to the extent that the relevant GA4GH group has started to avoid it altogether (except where it already existed due to history, e.g. Dockstore)

**Comment by coverbeck** [comment]
@geoffjentry What do you propose? This is all I can think of:

* workflow
* dockstore-tool
* dockstore-workflow
* method (as in the FireCloud methods repository)
* ???

Thanks,

Charles

**Comment by geoffjentry** [comment]
@coverbeck Is there an expectation that this is always going to refer to full workflows? If so I'd use that. If you're also expecting to reference individual tasks I think dockstore-tool is the best of those. Since you added it here, I'd also strongly suggest avoiding method in all contexts.

**Comment by denis-yuen** [comment]
Will likely refer to both full workflows and individual tasks long term. 
I'm ok with most of the names above except for method which would be confusing since it doesn't appear in TRS or Dockstore. 

(We use `Entry` as a base class for tools and workflows, so possibly `dockstore-entry`?)

**Comment by coverbeck** [comment]
OK, I will go with `dockstore-tool`, since we do plan to support individual tasks/tools. Will update PR.

**Comment by coverbeck** [comment]
@dvoet I see the Jenkins Automation Tests failed, but that server looks to be behind a firewall, so I can't see what's going on.

Do I need to worry about that? Are there tests that I can run locally to reproduce. I doubt I broke anything with just a config change (famous last words!), but maybe there are tests against the number of resource types or something like that?

**Pull request merged**
