### PR TITLE
ID-297 Update postgresql to 42.3.7

### PR DESCRIPTION
**Pull request by broadbot**
Updates [org.postgresql:postgresql](https://github.com/pgjdbc/pgjdbc) from 42.3.4 to 42.3.7.
[Changelog](https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md)

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/e93966d6d80e4ff1b31567984aa7e70e11cb2070/docs/repo-specific-configuration.md) file.

Have a fantastic day writing Scala!

<details>
<summary>Adjust future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "org.postgresql", artifactId = "postgresql" } ]
```
Or, add this to slow down future updates of this dependency:
```
dependencyOverrides = [{
  pullRequests = { frequency = "@monthly" },
  dependency = { groupId = "org.postgresql", artifactId = "postgresql" }
}]
```
</details>
<details>
<summary>Note that the Scala Steward config file `.scala-steward.conf` wasn't parsed correctly</summary>

```
cron4s.InvalidCron: Either DayOfMonth and DayOfWeek must have a ? expression: DownField(frequency),DownField(pullRequests)
```
</details>

labels: library-update, early-semver-patch, semver-spec-patch, commit-count:1

### CODE REVIEW

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Review by andy7i — APPROVED** [review]
👍

**Pull request merged**
