### PR TITLE
[CA-1859] Update sbt-scalafix to 0.10.0 in develop

### PR DESCRIPTION
**Pull request by broadbot**
Updates [ch.epfl.scala:sbt-scalafix](https://github.com/scalacenter/sbt-scalafix) from 0.9.34 to 0.10.0.
[GitHub Release Notes](https://github.com/scalacenter/sbt-scalafix/releases/tag/v0.10.0) - [Version Diff](https://github.com/scalacenter/sbt-scalafix/compare/v0.9.34...v0.10.0)

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/17235ca1e60ff61e35fe7b7cf51163a15ffc435d/docs/repo-specific-configuration.md) file.

Have a fantastic day writing Scala!

<details>
<summary>Ignore future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "ch.epfl.scala", artifactId = "sbt-scalafix" } ]
```
</details>

labels: sbt-plugin-update, early-semver-major, semver-spec-minor, commit-count:1

### CODE REVIEW

**Comment by andy7i** [comment]
jenkins retest -- test results no longer visible

**Comment by andy7i** [comment]
jenkins retest -- orch failed to start up https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/72867/console

```
Admin SA is registered but not fully enabled: RegistrationInfo(WorkbenchUserInfo(26517687256941274a5bd,firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com),WorkbenchEnabled(false,true,true),None)!

```

**Comment by andy7i** [comment]
jenkins retest
orch failed to start up. hmmmmm
https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/72876/console

looks like the same error
```
[WARN] [17:34:02.271] [scala-execution-context-global-102] o.b.dsde.firecloud.HealthChecks - SA registration lookup failed; attempting to register Admin SA. Lookup failure was: Admin SA is registered but not fully enabled: RegistrationInfo(WorkbenchUserInfo(2651771382147a712db1e,firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com),WorkbenchEnabled(false,true,true),None)!
```

**Comment by andy7i** [comment]
jenkins retest - fiab-start should work now

**Review by gpolumbo-broad — APPROVED** [review]

**Review by andy7i — COMMENTED** [review]
👍

**Pull request merged**
