### PR TITLE
[ca-1577] set up scala steward configs

### PR DESCRIPTION
**Pull request by andy7i**
Ticket: CA-1577
<Put notes here to help reviewer understand this PR>

Most of the code was pulled from https://github.com/DataBiosphere/leonardo (thanks to Qi)

See the commit history to view the changes made.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://broadinstitute.github.io/dsp-appsec-security-risk-assessment/) and attached the result to the JIRA ticket

### CODE REVIEW

**Review by ehigham — APPROVED** [review]

**Comment by andy7i** [comment]
@Qi77Qi tagged you for review since you created these files.

**Review by Qi77Qi — APPROVED** [review]

**Comment by andy7i** [comment]
jenkins retest
this looks unrelated

```
11:44:02 [info] - should list required authDomains and authDomains user is not a member of if constrainable *** FAILED ***
11:44:02 [info]   List() did not contain the same elements as Set(UserResourcesResponse(94b23375-35e2-4c93-bf45-3576d75c876a,RolesAndActions(Set(),Set()),RolesAndActions(Set(),Set()),RolesAndActions(Set(),Set()),Set(9e5920b7-5f2b-441a-8fa5-5c51625f4d72, ead775f7-0d62-41af-88bd-f32557cef5cc, d40fdb9a-592f-4941-bc79-ad0f66a342d1),Set(9e5920b7-5f2b-441a-8fa5-5c51625f4d72, ead775f7-0d62-41af-88bd-f32557cef5cc, d40fdb9a-592f-4941-bc79-ad0f66a342d1))) (PolicyEvaluatorServiceSpec.scala:565)
```
https://fc-jenkins.dsp-techops.broadinstitute.org/job/sam-build/3549/consoleFull

**Comment by andy7i** [comment]
jenkins retest
another unrelated failure
in `RegistrationApiSpec`
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-orchestration-fiab-test-runner/42048/console

**Comment by andy7i** [comment]
jenkins retest
another one!
```
WorkspaceApiSpec
```
https://fc-jenkins.dsp-techops.broadinstitute.org/job/rawls-fiab-test-runner/43553/console

**Pull request merged**
