### PR TITLE
Fix severe SA snafu

### PR DESCRIPTION
**Pull request by helgridly**
There was a bunch of confusion around `WorkbenchUserServiceAccountId`, which sometimes meant the unique "subject id" of the SA, and sometimes the left-part of its email. This clears up that confusion.

I have done this by making the "subject id" the bit that goes into LDAP, which I _think_ was the original intention. If it wasn't, and you'd rather it be the left-part of the email, LMK and I'll fix it.

Requires https://github.com/broadinstitute/workbench-libs/pull/38

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by helgridly** [comment]
> I have done this by making the "subject id" the bit that goes into LDAP, which I think was the original intention. If it wasn't, and you'd rather it be the left-part of the email, LMK and I'll fix it.

Given that tests are failing I think I am wrong here. Am I?

**Comment by helgridly** [comment]
Wait, no. Because LDAP is storing a `WorkbenchSubject`, which is a subject id. I'm so confused.

**Comment by rtitle** [comment]
Uh, it's failing here:
```
[info] - should get a pet service account for a user *** FAILED ***
[info]   None was not equal to Some(WorkbenchUserServiceAccount(1234567890,pet-newuser@my-pet-project.iam.gserviceaccount.com,)) (UserServiceSpec.scala:149)
```
but I don't see the bug (yet). It looks correct..

**Comment by helgridly** [comment]
The problem is I'm trying to store a subject ID in Sam LDAP now. This works fine everywhere except for `loadPetServiceAccount`, which takes a subject ID nobody knows about and can't ascertain because it's Google-generated. And we're no longer storing the account name in Sam. If we try to store the account name in Sam then that fails because the account name isn't a `WorkbenchSubject`. I am beginning to think the answer is we store both in LDAP.

**Comment by rtitle** [comment]
Ah yeah, I see. `MockGoogleIamDAO` does this for the subject ID: 
```
val uniqueId = WorkbenchUserServiceAccountUniqueId(Random.nextLong.toString)
```
and `UserService.createUserPetServiceAccount` doesn't return back the subject ID, just the email.

Maybe `UserService.createUserPetServiceAccount` should return back the full `WorkbenchUserPetServiceAccount` so the caller can see _both_ the subject ID and email which were generated. Then the test could call `loadPetServiceAccount` with the subject ID that was returned by `createUserPetServiceAccount`.

**Comment by rtitle** [comment]
...or just make `MockGoogleIamDAO` deterministic as it was before, so you can verify with tests. :)

I don't think this is a problem outside of unit tests..

**Comment by helgridly** [comment]
We need to store both the subject id and email. We look up using the email, but need a WorkbenchSubject for `dnToSubject`.

**Comment by helgridly** [comment]
Either that or I'm severely misunderstanding what Sam wants to store in a dn.

**Comment by rtitle** [comment]
I think you may be misunderstanding a little (or I am).

The subject is always in the dn (the "primary key"). This was true before this change. The other fields are stored as attributes. For example:

```
ou=people:
  subject: 123   <-- this is in the dn
    email: rtitle@broadinstitute.com  <-- attribute
    pet: pet-123@gserviceaccount.com   <-- attribute

ou=pets:
  subject: 456   <-- this is in the dn
    email: pet-123@gserviceAccount.com  <-- attribute
```

This way a "person" (e.g. rtitle@broadinstitute.org) can easily look up its pet email. And incoming requests _as the pet_ can easily switch back to the user (the user subject ID is embedded in the pet email).

The issue with this test is you're generating random pet subject IDs, and have no way to retrieve them afterwards. I think that can be resolved with better mocks.

**Comment by dvoet** [comment]
that last comment looks right and if there is still confusion let's use faces.

I would like to eventually see either of 2 things 1) the pet attribute of a person stores the dn of the pet, not the email or 2) pets live beneath their user in the directory hierarchy, not in a separate ou.

**Comment by rtitle** [comment]
@dvoet I was going to try your #2, I haven't got it to a PR stage yet.

**Review by rtitle — APPROVED** [review]
I threw this on a fiab and it works. :shipit: after fixing namings.

**Pull request merged**
