### PR TITLE
ID-364 No more firestore, no more firestore credentials

### PR DESCRIPTION
**Pull request by tlangs**
Ticket: https://broadworkbench.atlassian.net/browse/ID-364

What:

Getting rid of references to the Firestore SA credentials

Why:

Since Sam no longer uses Firestore for its distributed lock, there's no reason to reference the service account! The code already doesn't reference the account, but the config files still do. Removing the references here will mean terra-helmfile and firecloud-develop don't need to render the accounts. Then, we can nuke the `broad-wb-firestore` projects! Plus, its one less key to keep track of!

How:

Deletin' lines

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

### CODE REVIEW

**Comment by tlangs** [comment]
jenkins retest

**Review by andy7i — COMMENTED** [review]
I see a few more references to firestore after checking out the branch and searching the repo. Some of them are generated from the scripts in fc-dev -- do we want to remove those as part of this ticket or create followup tickets for that?

**Comment by tlangs** [comment]
@andy7i Yup! https://github.com/broadinstitute/firecloud-develop/pull/3192

**Comment by tlangs** [comment]
jenkins retest

**Review by andy7i — APPROVED** [review]

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Review by Shakespeared — APPROVED** [review]

**Pull request merged**
