### PR TITLE
[DC-1116] Move from set_parent to create_with_parent

### PR DESCRIPTION
**Pull request by s-rubenstein**
Ticket: https://broadworkbench.atlassian.net/browse/DC-1116
  \<Don't forget to include the ticket number in the PR title!\>

What:

  \<For your reviewers' sake, please describe in a sentence or two what this PR is accomplishing (usually from the users' perspective, but not necessarily).\>

Why:

  \<For your reviewers' sake, please describe in ~1 paragraph what the value of this PR is to our users or to ourselves.\>

How:

  \<For your reviewers' sake, please describe in ~1 paragraph how this PR accomplishes its goal.\>

  \<If the PR is big, please indicate where a reviewer should start reading it (i.e. which file or function).\>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

### CODE REVIEW

**Review by rjohanek — COMMENTED** [review]
this looks good but how can we test this change?

**Comment by s-rubenstein** [comment]
@rjohanek I think the only real way to test it is to spin up a BEE? Which has proven somewhat difficult, but I think might be possible.

Alternatively, the rollback for this is very fast, and it should be easy to test post merge - I think that the real question is whether there is testing for the create_with_parent action, and that is probably out of scope. (and likely already done by identiteam when they released the feature)

**Comment by s-rubenstein** [comment]
Actually, I could maybe spin up a local Sam and try creating a request resource with a parent, just using the resources APIs. I might try that rather than fiddling with bees

**Review by rjohanek — APPROVED** [review]
looks good, proposed plan for testing sounds good!

**Comment by s-rubenstein** [comment]
I tested by locally running Sam, creating a datasnapshot resource by hand, and then creating a `snapshot-access-request` resource by hand with that snapshot resource as the parent.

**Review by snf2ye — APPROVED** [review]

**Pull request merged**
