### PR TITLE
[CA-1871] tag PRs with a default ticket number

### PR DESCRIPTION
**Pull request by andy7i**
Ticket: [CA-1871](https://broadworkbench.atlassian.net/browse/CA-1871)

to be compliant with Compliance requirements, add a ticket number to all Scala Steward PRs, specifically this ticket: https://broadworkbench.atlassian.net/browse/CA-1858

<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://broadinstitute.github.io/dsp-appsec-security-risk-assessment/) and attached the result to the JIRA ticket

### CODE REVIEW

**Comment by andy7i** [comment]
jenkins retest
this looks unrelated:
```
Error Message
{&#010;  "causes": [],&#010;  "message": "Google Id 117891551413045861932 not found in sam",&#010;  "source": "sam",&#010;  "stackTrace": [],&#010;  "statusCode": 403,&#010;  "timestamp": 1651091732779&#010;}
```
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-orchestration-fiab-test-runner/42060/testReport/junit/org.broadinstitute.dsde.test.api.orch/RegistrationApiSpec/FireCloud_registration_should_allow_a_person_to_register/

**Review by ehigham — CHANGES_REQUESTED** [review]
While I understand the necessity, I can't say I like this design very much as it proliferates zombie tickets that will never ever die. The walking dead had to end at some point. That show dragged.
I think it would be better if each PR automatically created it's own ticket. I have no idea how to do that however so willing to put heads together if you're interested, but I think it would grant the higher-ups more insight into upcoming work that needs scheduling.

**Comment by andy7i** [comment]
@ehigham I like that idea and can create a ticket for it. I'm a little worried that we might not be able to pick up that work for a while. That would mean that we need to add ticket #s manually to each Scala Steward PR until that ticket is completed. Do you think this PR can work as a stop gap until then?

**Comment by andy7i** [comment]
created https://broadworkbench.atlassian.net/browse/CA-1871

**Pull request closed without merging**
