### PR TITLE
ID-281 - add liveness test

### PR DESCRIPTION
**Pull request by andy7i**
Ticket: https://broadworkbench.atlassian.net/browse/ID-281

What:

We want a liveness that is separate from the readiness test so that k8 can kill bad pods.

Why:
Jack explained the reasoning for this:
> Jack Warren  [16 hours ago](https://broadinstitute.slack.com/archives/C03GMG4DUSE/p1664317959527059?thread_ts=1664305070.677259&cid=C03GMG4DUSE)
> Re “why doesn't k8s restart pods when /status fails”—because all apps except Leonardo don't respond at all over the wire until after their entire boot process and database migration is complete. If we kill a pod that's not dead, just busy and hasn't come online yet or isn't online temporarily, that's a corrupt database and a huge problem
> 
> k8s will restart applications with failing /status usually within several hours
> 
> If an application adds a separate /liveness endpoint that comes online at the very beginning of the boot process, like Leonardo added, we can configure very tight health checks against both the app and its Apache proxy to automatically restart when there's failures, usually before an external uptime monitor would notice anything (edited) 
> 
> We cannot safely do that until apps expose an endpoint made for it though. That endpoint must be built with the understanding that if it ever fails or is slow, the app container gets killed very very quickly1
> 

How:

> :9000/liveness is the first thing that comes online. It just returns 200 OK as long as the executable is running

Most of this is taken from Leonardo's implementation.

I tested this locally (with changes in https://github.com/broadinstitute/firecloud-develop/pull/3179, which will be merged first ; Terra-helmfile PR TBD.) and the proxy port was opened up at :9000 and the /liveness endpoint worked as expected.

---

**PR checklist**

- [x] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [x] I've filled out the [Security Risk Assessment](https://broadinstitute.github.io/dsp-appsec-security-risk-assessment/) and attached the result to the JIRA ticket

[ID-281]: https://broadworkbench.atlassian.net/browse/ID-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by andy7i** [comment]
jenkins retest

**Comment by andy7i** [comment]
tests passed here: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/73023/
not sure why it isn't showing up in the list of checks.

**Comment by andy7i** [comment]
jenkins retest - BEEs should be fixed now

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Comment by Ghost-in-a-Jar** [comment]
The only thing id be worried about is the liveness server process blocking the other stuff, when testing locally make sure the regular api works as well etc. Im sure jenkens tests would catch that though.

**Review by Shakespeared — APPROVED** [review]

**Review by gpolumbo-broad — APPROVED** [review]

**Comment by andy7i** [comment]
> The only thing id be worried about is the liveness server process blocking the other stuff, when testing locally make sure the regular api works as well etc. Im sure jenkens tests would catch that though.

@Ghost-in-a-Jar 
good idea. I tested some other user APIs and they worked ok.

**Comment by andy7i** [comment]
jenkins retest

**Comment by andy7i** [comment]
jenkins retest

**Comment by andy7i** [comment]
jenkins retest

**Comment by andy7i** [comment]
jenkins retest

**Comment by andy7i** [comment]
jenkins retest

**Pull request merged**
