### PR TITLE
ID-527 Upgrade json-smart to 2.4.10

### PR DESCRIPTION
**Pull request by tlangs**
Ticket: https://broadworkbench.atlassian.net/browse/ID-527

What:

Upgrading the `json-smart` transitive dependency to 2.4.10.

Why:

Upgrading the `json-smart` transitive dependency because of a vulnerability.

How:

Upgrading it in `Dependencies.scala`

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

### CODE REVIEW

**Review by Shakespeared — APPROVED** [review]

**Comment by davidangb** [comment]
fyi, an update to `azure-identity` to resolve the transitive dependency is imminent, per [this comment](https://github.com/Azure/azure-sdk-for-java/issues/34223#issuecomment-1495175620)

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Comment by tlangs** [comment]
@davidangb Oh, I may just wait for that then.

**Comment by zloery** [comment]
As a heads-up, we've published version `1.2.12` of CRL with the newer `azure-identity` dependency

**Comment by tlangs** [comment]
Awesome! I'll use that instead

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Comment by tlangs** [comment]
jenkins retest

**Pull request merged**
