### PR TITLE
CA-240 Added "service-perimeter" as new resource type

### PR DESCRIPTION
**Pull request by gpolumbo-broad**
Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

### CODE REVIEW

**Comment by RLuckom** [comment]
jenkins reteest

**Comment by RLuckom** [comment]
jenkins retest

**Comment by RLuckom** [comment]
jenkins retest

**Comment by RLuckom** [comment]
jenkins retest

**Review by dvoet — APPROVED** [review]

**Comment by dvoet** [comment]
automation tests launched manually and passed https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Pipelines/job/swatomation-pipeline/20155/

**Review by marctalbott — APPROVED** [review]

**Pull request merged**
